# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "request.HelloRequest" do
    optional :msg, :string, 1
    optional :inner, :message, 2, "request.InnerRequest"
    optional :n, :int64, 3
    optional :ptype, :enum, 4, "request.PhoneType"
  end
  add_message "request.InnerRequest" do
    optional :msg, :string, 1
    optional :n, :int64, 2
    optional :ptype, :enum, 3, "request.PhoneType"
  end
  add_message "request.HelloResponse" do
    optional :msg, :string, 1
  end
  add_message "request.HelloStreamRequest" do
    optional :msg, :string, 1
  end
  add_message "request.HelloStreamResponse" do
    optional :msg, :string, 1
  end
  add_enum "request.PhoneType" do
    value :MOBILE, 0
    value :HOME, 1
    value :WORK, 2
  end
end

module Request
  HelloRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("request.HelloRequest").msgclass
  InnerRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("request.InnerRequest").msgclass
  HelloResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("request.HelloResponse").msgclass
  HelloStreamRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("request.HelloStreamRequest").msgclass
  HelloStreamResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("request.HelloStreamResponse").msgclass
  PhoneType = Google::Protobuf::DescriptorPool.generated_pool.lookup("request.PhoneType").enummodule
end
