# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: request.proto for package 'request'

require 'grpc'
require 'examples/request/request_pb'

module Request
  module Request
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'request.request'

      rpc :Hello, HelloRequest, HelloResponse
      rpc :HelloServerStream, HelloRequest, stream(HelloStreamResponse)
      rpc :HelloClientStream, stream(HelloStreamRequest), HelloResponse
      rpc :HelloStream, stream(HelloStreamRequest), stream(HelloStreamResponse)
    end

    Stub = Service.rpc_stub_class
  end
end
